<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library[
<!ELEMENT library (book)*>
<!ELEMENT book (booktitle, author, price)+>
<!ELEMENT booktitle (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]>
<library>
    <book>
        <booktitle>The Firm</booktitle>
        <author>John Grisham</author>
        <price>99</price>
    </book>
    <book>
        <booktitle>Coma</booktitle>
        <author>John Grisham</author>
        <price>99</price>
    </book>
    <book>
        <booktitle>The Firm</booktitle>
        <author>John Grisham</author>
        <price>99</price>
    </book>
</library>
